// IMPORT LIBRARIES/DEPENDENCIES
const express = require('express'); // IMPORT THE EXPRESS FRAMEWORK
const cors = require('cors'); // IMPORT THE CORS LIBRARY ENABLING CROSS-ORIGIN RESOURCE SHARING
const dotenv = require('dotenv'); // IMPORT THE DOTENV LIBRARY TO LOAD ENVIRONMENT VARIABLES FROM THE .ENV FILE

dotenv.config(); // LOADS THE ENVIRONMENT VARIABLES FROM THE .ENV FILE

// IMPORT ROUTES
const users = require('./routes/users'); // IMPORT THE USERS ROUTER
const logger = require('./middleware/logger'); // IMPORT THE LOGGER MIDDLEWARE
const auth = require('./authorization/auth'); // IMPORT THE AUTH ROUTER/MIDDLEWARE

// CREATE AN INSTANCE OF THE EXPRESS APPLICATION
// CREATES A NEW EXPRESS APP (THIS APPLICATION)
const app = express(); 

app.use(cors()); // ENABLE CROSS-ORIGIN RESOURCE SHARING FOR THIS APPLICATION // SO FRONTEND AND THIS API CAN COMMUNICATE WITH EACH OTHER
app.use(express.json()); // PARSE INCOMING REQUESTS WITH JSON PAYLOADS // ALLOWS THE API TO READ JSON DATA FROM THE REQUEST BODY

// MIDDLEWARE
app.use(logger); // LOG THE REQUEST METHOD AND URL

// DEFINE ROUTES/ API ENDPOINTS
app.use('/api/users', users); // WHEN A REQUEST IS MADE TO THE /API/USERS PATH, THE USERS ROUTER WILL ROUTE THE REQUEST TO THE APPROPRIATE ENDPOINT BASED ON THE REQUEST PATH
app.use('/api/auth', auth); // WHEN A REQUEST IS MADE TO THE /API/AUTH PATH, THE AUTH ROUTER WILL ROUTE THE REQUEST TO THE APPROPRIATE ENDPOINT BASED ON THE REQUEST PATH

// START THE SERVER
const PORT = process.env.PORT;

// ALLOWS THIS API APPLICATION TO LISTEN FOR INCOMING API REQUESTS ON THE SPECIFIED PORT
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
